export enum SunlightIncidenceEnum {
  FULL_SHADE = "FULL_SHADE",
  PART_SHADE = "PART_SHADE",
  SUN_PART_SHADE = "SUN_PART_SHADE",
  PART_SUN_PART_SHADE = "PART_SUN_PART_SHADE",
  FULL_SUN = "FULL_SUN",
}
